
[phases.setup]
nixPkgs = ['nodejs']  # Instala Node.js y Yarn

[phases.install]
cmds = ['npm install']  # Instala las dependencias del proyecto usando Yarn

[phases.build]
cmds = ['npm run build']  # Construye la aplicaci贸n de React

# Define c贸mo debe iniciarse la aplicaci贸n
[start]
cmd = 'npm run start'  # Sirve la aplicaci贸n React construida desde la carpeta 'build' en el puerto 5173

[project]
directory = '/'